name: aicycle_claimme_lib
description: An AiCycle ClaimMe package.
version: 0.1.4
homepage: https://aicycle.ai/

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  camera: ^0.10.5+5
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter_image_compress: ^2.1.0
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  get: ^4.6.6
  image: ^4.1.3
  image_picker: ^1.0.4
  logger: ^2.0.2+1
  mime: ^1.0.4
  path: ^1.8.3
  path_provider: ^2.1.1
  photo_view: ^0.14.0
  readmore: ^2.2.0
  sensors_plus: ^4.0.2
  top_snackbar_flutter: ^3.1.0
  shimmer: ^3.0.0
  geolocator: ^11.0.0
  latlong2: ^0.9.0
  geocoding: ^3.0.0
  exif: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/gif/