name: aicycle_claimme_plus
description: "An AICycle ClaimMe Plus package."
version: 1.0.4
homepage: https://aicycle.ai/

environment:
  sdk: ^3.11.1
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.4.1
  camera: ^0.12.0
  dio: ^5.9.2
  flutter:
    sdk: flutter
  image_picker: ^1.2.1
  native_device_orientation: ^2.1.0
  image: ^4.5.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gif/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
