name: aicycle_claimme_lib
description: An AiCycle ClaimMe package.
version: 0.3.0
homepage: https://aicycle.ai/

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  camera: ^0.11.2
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter_image_compress: ^2.4.0
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  get: ^4.7.2
  image: ^4.5.4
  image_picker: ^1.2.0
  logger: ^2.6.1
  mime: ^2.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  readmore: ^3.0.0
  sensors_plus: ^7.0.0
  top_snackbar_flutter: ^3.3.0
  shimmer: ^3.0.0
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  geocoding: ^4.0.0
  exif: ^3.3.0
  saver_gallery: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/gif/
